<?php
/** @var \Magento\Sales\Block\Order\History $block */
$_orders = $block->getOrders();
$_order = null;
$viewModel = $block->getData('viewModel');
?>

<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                        </td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                            <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($viewModel->canReorder($_order->getEntityId())): ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                    $viewModel->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                            <?php if ($viewModel->isOrderCancel($_order->getEntityId())): ?>
                                <a href="<?= $block->escapeHtml(__($viewModel->getSalesOrderUrl($_order))) ?>"
                                class="viewCancelOrderStatus" id="<?= $block->escapeHtml(__($_order->getId()))?>">
                                    <span><?=$block->escapeHtml(__('View Status')) ?></span>
                                </a>
                                <?php else: ?>
                                    <?php if ($_order->getStatus() !== 'canceled'
                                    && $_order->getStatus() !== 'complete'):?>
                                        <a href="#" class="click-me"
                                        id="<?= $block->escapeHtml(__($_order->getId()))?>">
                                            <span><?=$block->escapeHtml(__('Cancel Order')) ?></span>
                                        </a>
                                    <?php endif ?>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>
    <?php else: ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<div class="popup-modal" style="display:none;">
    <form action="#" method="post" class="form-validate" enctype="multipart/form-data"
    autocomplete="off" data-mage-init='{"validation":{}}'
    data-hasrequired="<?= /* @escapeNotVerified */$block->escapeHtml(__('* Required Fields'))  ?>">
    <?php $questions = $viewModel->getQuestions() ?>
    <?php if ($questions && $_order):?>
        <select name="reason" class="">
                <?php foreach ($questions as $question):?>
                    <option value="<?= $block->escapeHtml($question) ?>"><?= $block->escapeHtml($question)?></option>
                <?php endforeach;?>
            </select>
            <input type="hidden" id="orderId" name="orderId" Value="<?= $block->escapeHtml($_order->getId())?>">
        </form>
    <?php endif;?>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                title: 'Reason for Cancelled the item',
                buttons: [{
                    text: $.mage.__('submit'),
                    class: '',
                    click: function(data) {
                        var form_data = jQuery(".form-validate").serialize();
                        console.log(form_data);
                        jQuery.ajax({
                            url: "<?= $block->escapeHtml($block->getBaseUrl()) . 'cancelorder/index';?>",
                            type: 'POST',
                            data: form_data,
                            success: function(data) {
                                window.location.href = "<?= $block->escapeHtml($block->getBaseUrl())
                                . 'sales/order/history';?>";
                            },
                            error: function(result) {
                                console.log('Something went wrong!');
                            }
                        });
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('.popup-modal'));
            $(".click-me").on('click', function() {
                var orderId = $(this).attr("id");
                $(".popup-modal").modal("openModal");
                ($("#orderId").attr("value",orderId));
            });

        }
    );
</script>
